site_author: "Joel de Guzman"
site_dir: "_site"
remote_branch: "www"

extra:
  generator: true

plugins:
  search: {}

extra_css:
- common/stylesheets/github.css

markdown_extensions:
# admonition: {}
# attr_list: {}
# md_in_html: {}
# pymdownx.details: {}
  pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
  pymdownx.highlight:
    anchor_linenums: true
# pymdownx.inlinehilite: {}
# pymdownx.snippets: {}
  pymdownx.superfences: {}
# pymdownx.tabbed:
#   alternate_style: true
  tables: {}

theme:
  name: "material"
  icon:
    repo: "fontawesome/brands/github"
    edit: "material/pencil"
    view: "material/eye"
  font: false
  palette:
  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: "default"
    toggle:
      icon: "material/weather-night"
      name: "Switch to dark mode"
  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: "slate"
    toggle:
      icon: "material/weather-sunny"
      name: "Switch to light mode"
  features:
  - content.action.edit
  - content.action.view
  - content.code.copy
  - header.autohide
# - navigation.footer
  - navigation.top
# - toc.integrate

# name: "readthedocs"
# sticky_navigation: false
# include_homepage_in_sidebar: false
# nav_style: dark
